apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deploy
  namespace: webs-app
  labels:
    app: web-app
spec:
  selector:
    matchLabels:
      app: web-app
  replicas: 2
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: omarzaki222/my-website-image
          ports:
            - containerPort: 8087