apiVersion: v1
kind: Service
metadata:
  name: web-app
  namespace: webs-app
  labels:
    app: web-app
spec:
  selector:
    app: web-app
# ClusterIP (default), LoadBalancer (works on cloud), NodePort (most used)
  type: LoadBalancer
  ports:
  - port: 8087
    targetPort: 8087